config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'todo/index'
  resources :todos

  authenticated :user do
  root :to => 'todos#index', :as => :authenticated_root
end
root :to => redirect('/users/sign_in')

end

app/models/todo.rb
class Todo < ActiveRecord::Base

  belongs_to :user

  def self.complete ids
      ids.each do |id|
        current_todo = Todo.find(id)
        current_todo.update(Complete: true)
      end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!, only:[:new, :create]

  def index
    completed_todos_ids = params[:todos_ids]
    Todo.complete(completed_todos_ids) 
    @todo = current_user.todos.where(Complete: nil).order(:Priority)
    
  end

  def show
    @todo = Todo.order(:Priority)
  end

  def time_format
    @todo = Todo.Time_Estimate.to_formatted_s(:long)
  end

  def nil.each
    puts "hey"
  end

  def new
    @todo = Todo.new
  end
  
  def update
    @todo = Todo.find params[:id]
    @todo.update todo_params

    redirect_to todos_path
  end

  def create
    @todo = current_user.todos.new(todo_params)

    if @todo.save 
      redirect_to todos_path
    else
      render 'new'
    end
  end
  
  def edit
    @todo = Todo.find params[:id]
  end

  def destroy
    @todo = Todo.find params[:id]
    @todo.destroy

    redirect_to todos_path
  end

  def complete
    @todo = Todo.find params[:id]
    @odo.update(:Compelete => "true")
  end

  private  
  def todo_params
   params.require('todo').permit(:Priority, :Action, :Description, :Time_Estimate, :Deadline)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Explore</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	
	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/todos">Explorer</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling 
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->
      <ul class="nav navbar-nav navbar-right">
      	  <% if user_signed_in? %>
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign in", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
	<body>
		


	<div class='container'>

	<%= yield %>
	</div>
	</body>
</html>

app/views/todos/_form.html.erb
<%= form_for @todo, :html => {:class => 'form-horizontal'} do |f| %>		

<div class='container', align='center'>
  <fieldset>
    <div class="control-group">
      <%= f.label :Action, :class => 'control-label' %>
      <div class="controls", size="50">
        <%= f.text_field :Action, :class => 'text_field' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :Description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :Description, :class => 'text_field' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :Deadline, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :Deadline, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :Time_Estimate, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :Time_Estimate, :class => 'text_field' %>
      </div>

    <div class="control-group">
      <%= f.label :Priority, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :Priority, :class => 'text_field' %>
      </div>

      <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', todos_path, :class => 'btn btn-danger' %>
    </div>
    </div>
  </fieldset>
</div>
<% end %>

app/views/todos/edit.html.erb
<div class='container', align='center'>
  <h1> 
    Edit a To Do 
  </h1>
</div>
  <body>
    <%= render 'form' %>
  </body>

app/views/todos/index.html.erb
<%= form_tag "/", method:'GET' do %>
<table class="table table-striped">

  </div>

	<thead>
		<tr>
			<th>Complete</th>
			<th>Priority</th>
			<th>To Do</th>
			<th>Description</th>
			<th>Time Estimate</th>
			<th>Deadline</th>
			<th>Actions</th>
		</tr>
	</thead>
	<body>
		<% @todo.each do |todo| %>	

		<tr>
			<td><%= check_box_tag "todos_ids[]", todo.id %></td>
			<td><%= todo.Priority %></td>
			<td><%= todo.Action %></td>
			<td><%= todo.Description %></td>
			<td><%= todo.Time_Estimate.strftime("%H:%M") unless todo.Time_Estimate.blank? %></td>
			<td><%= todo.Deadline.strftime("%B %e, %Y") unless todo.Deadline.blank?%></td>
			<td><%= link_to 'Edit', edit_todo_path(todo), :class => 'btn btn-mini btn-info' %> 
			<%= link_to 'Delete', todo_path(todo), 
				method: :delete, 
				data: {confirm: 'Are you sure?'}, :class => 'btn btn-mini btn-danger' %></td>
			<p1><%= Todo.where(Complete: nil).sum(:Time_Estimate) %></p1>	
		<%end%>
		</tr>
		
	</body>
	
		<% end %>
	

	<nav class="navbar navbar-inverse navbar-fixed-bottom">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>


      <ul class="nav navbar-nav navbar-right">
      	<li><%= link_to 'Add new To Do', new_todo_path, 
			:class => 'btn btn-mini btn-success' %></li>
		<li><%= submit_tag("Remove Completed Tasks") %></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/todos/new.html.erb
<div class='container', align='center'>
  <h1> 
    Add a To Do 
  </h1>
</div>
  <body>
    <%= render 'form' %>
  </body>